### ISSUE TITLE
Running the trained model on the Bittle

### ISSUE THREAD

**Issue by ricardofauch** [ger01d/opencat-gym#3]
Hello,

I would like to run this trained model on my Petoi Bittle and test it in the real world. However, I am unsure how to proceed with running this model directly on the Bittle's Arduino board.

Could you please provide guidance or steps on how to execute a trained RL model on the Bittle? Specifically, I am looking for information on:

1. Whether it's feasible to run a trained RL model directly on the Arduino board of the Bittle.
2. If not, what is the recommended approach to control the Bittle using a trained RL model.
3. Any examples or documentation that detail the process of integrating a trained model with the Bittle's hardware and software.

Thank you for your assistance!

Best regards

**Comment by ger01d** [comment]
Hello ricardofauch,

to answer your questions:
1. The trained model is not intended to run on the Arduino directly, since it relies on the python libraries like PyTorch.

2. You can take a look at the sim2real transfer in my repository, where you can run the trained network on a computer and control Bittle via the serial port [opencat-gym-sim2real](https://github.com/ger01d/opencat-gym-sim2real). 

Currently I'm using the ESP32-board (BiBoard from Petoi), because I have a lower latency in the serial communication. So for the Arduino (NyBoard) it won't work without adaptions.

**Comment by ger01d** [comment]
No more feedback from the questioner.
